### ISSUE TITLE
Project stalled?

### ISSUE THREAD

**Issue by igoramadas** [bunqCommunity/bunqAutomation#10]
Is this still going forward?

I just started working on a [similar project](https://github.com/igoramadas/jarbunq) before I found out about this one. Mine is not supposed to be a full-fledged automation server, but depending on the ideas and timeline I might simply drop it and help working on yours instead.

Right now I have already implemented some email parsing and a "Strava mileage savings" features.

**Comment by Crecket** [comment]
I'm busy with other projects, school and work at the moment so I'm not actively working on the bunq projects for now. You can contribute ofcourse but this automation project still needs quite a bit of work to get to the point where I would want it.

**Comment by igoramadas** [comment]
Sure, first things first :-) I'll keep an eye on the project then. For now will keep working on my own.

Good luck with your studies!
