### ISSUE TITLE
API

### ISSUE THREAD

**Issue by readefries** [bunqCommunity/bunqAutomation#7]
An API would be awesome! So we could make an app to connect to it.

- [ ] OAuth support
- [ ] Registration API
- [ ] Actions API
- [ ] Filters API
- [ ] Outputs API

**Comment by Crecket** [comment]
Everything is done through an API so besides the OAuth part you can already do everything through it. 

You can authenticate with a password to retrieve an API key so there is no advanced user/permission system as of now.

**Comment by readefries** [comment]
Awesome!
